### ISSUE TITLE
笔误？

### ISSUE THREAD

**Issue by samrayleung** [xianhu/LearnPython#17]
`python_base.py`

`set是可变对象，即不存在hash值，不能作为字典的键值。同样的还有list、tuple等
    frozenset是不可变对象，即存在hash值，可作为字典的键值
    frozenset对象没有add、remove等方法，但有union/intersection/difference等方法`
tuple 是不可变对象，这里是笔误么?

**Comment by xianhu** [comment]
嗯，谢谢指正。
