### ISSUE TITLE
Change Navbar -> NavbarSimple

### ISSUE THREAD

**Issue by tcbegley** [xianhu/LearnPython#38]
Hi

Thanks for using *dash-bootstrap-components*! I just wanted to let you know that we made a breaking change to the `Navbar` component, so if you update to version `0.3.0` or later of *dash-bootstrap-components* you might get unexpected behaviour. 

You can use the new `NavbarSimple` component exactly as you are currently using `Navbar` currently, so the easiest fix would be to just change `Navbar` to `NavbarSimple`.

Check out [the docs for `Navbar`](https://dash-bootstrap-components.opensource.asidatascience.com/l/components/navbar) and [our examples](https://github.com/ASIDataScience/dash-bootstrap-components/blob/master/examples/advanced-component-usage/Navbars.py) for more details.

**Comment by xianhu** [comment]
OK, Thanks
